[package]
name = "ochre"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2018"

[dependencies]
gl = "0.11.0"

[dev-dependencies]
glutin = "0.21.0"
usvg = "0.9.0"
rayon = "1.3.0"

[profile.release]
debug = true
